"""Coach agent — runs at round end, produces the full Debrief.

The Coach is the ONLY agent that gives feedback. It never breaks the opponent's
character mid-round. It receives:
  - transcript: the full conversation
  - move_events: list[MoveEvent] from the Adjudicator
  - playbook: the user-side Playbook
  - opp_playbook: OpponentPlaybook (revealed post-round as coaching)
  - score_data: already-computed deterministic scores from scoring.py
  - persona_name: which persona was played

Prose fields (turning_point_explainer, stronger_move, persona_note) are
generated by the model. All other Debrief fields are computed deterministically
in scoring.py before the Coach is called.
"""
from __future__ import annotations
import json
import re
from crucible.agents.base import ModelClient
from crucible.schemas import Debrief, MoveEvent, OpponentPlaybook, Playbook


def _build_system_prompt(
    playbook: Playbook,
    opp_playbook: OpponentPlaybook,
    move_events: list[MoveEvent],
    turning_point_turn: int,
    persona_name: str,
    score: int,
    score_to_beat: int | None,
) -> str:
    events_text = "\n".join(
        f"  Turn {e.turn}: [{e.classification}] refs={e.refs} delta={e.position_delta:+.2f} — {e.note}"
        for e in move_events
    )
    opp_ladder_text = "\n".join(
        f"  Rung {i}: {r.position}\n    Would have unlocked if: {r.unlock_condition}"
        for i, r in enumerate(opp_playbook.concession_ladder)
    )
    beat_str = f"Previous best: {score_to_beat}" if score_to_beat is not None else "First round"
    return f"""You are a senior legal training coach reviewing a completed negotiation round.
This round's score: {score}/100. {beat_str}.

The trainee played against persona: {persona_name}.

TURN-BY-TURN ADJUDICATOR LOG:
{events_text}

TURNING POINT: Turn {turning_point_turn} was identified as the critical moment.

USER-SIDE PLAYBOOK (what they were trying to achieve):
Matter: {playbook.matter_summary}
Objectives: {playbook.objectives}

OPPONENT'S HIDDEN CONCESSION LADDER (revealed now for coaching):
{opp_ladder_text}

Your task: produce three specific, grounded coaching outputs in JSON:
{{
  "turning_point_explainer": "<2-3 sentences: what went wrong or right at turn {turning_point_turn} AND what the great-lawyer alternative was>",
  "stronger_move": "<the single best alternative move for the worst moment — cite the specific legal hook that would have worked>",
  "persona_note": "<one sentence on how the {persona_name} persona was exploiting this trainee's pattern and how to counter it next round>"
}}

Rules:
- Be specific — reference actual turn numbers, specific legal articles, specific words said
- Never say "you should have been more confident" — that is not coaching, that is vague
- The stronger_move must be actionable: a specific argument with a specific legal ground
- Return ONLY the JSON object above
"""


def _extract_json(raw: str) -> dict:
    raw = raw.strip()
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw, re.DOTALL)
    if m:
        return json.loads(m.group(1))
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start != -1 and end > start:
            return json.loads(raw[start:end])
        raise ValueError(f"Could not extract JSON from coach response: {raw[:200]!r}")


class CoachAgent:
    def __init__(self, client: ModelClient, model: str) -> None:
        self._client = client
        self._model = model

    def produce_debrief(
        self,
        transcript: list[dict],
        move_events: list[MoveEvent],
        playbook: Playbook,
        opp_playbook: OpponentPlaybook,
        persona_name: str,
        score: int,
        subscores: dict[str, int],
        turning_point_turn: int,
        score_to_beat: int | None,
        biggest_concession: MoveEvent | None,
        biggest_miss: MoveEvent | None,
        biggest_overplay: MoveEvent | None,
        stronger_move_authorities: list,
    ) -> Debrief:
        system = _build_system_prompt(
            playbook,
            opp_playbook,
            move_events,
            turning_point_turn,
            persona_name,
            score,
            score_to_beat,
        )
        raw = self._client.generate(
            model=self._model,
            system=system,
            messages=transcript,
        )
        parsed = _extract_json(raw)
        return Debrief(
            score=score,
            subscores=subscores,
            score_to_beat=score_to_beat,
            turning_point_turn=turning_point_turn,
            turning_point_explainer=str(parsed.get("turning_point_explainer", "")),
            stronger_move=str(parsed.get("stronger_move", "")),
            stronger_move_authorities=stronger_move_authorities,
            biggest_concession=biggest_concession,
            biggest_miss=biggest_miss,
            biggest_overplay=biggest_overplay,
            persona_note=str(parsed.get("persona_note", "")),
        )
