"""Coach agent — runs at round end, produces the full Debrief.

The Coach is the ONLY agent that gives feedback. It never breaks the opponent's
character mid-round. It receives:
  - transcript: the full conversation
  - move_events: list[MoveEvent] from the Adjudicator
  - playbook: the user-side Playbook
  - opp_playbook: OpponentPlaybook (revealed post-round as coaching)
  - score_data: already-computed deterministic scores from scoring.py
  - persona_name: which persona was played

Prose fields (turning_point_explainer, stronger_move, persona_note) are
generated by the model. All other Debrief fields are computed deterministically
in scoring.py before the Coach is called.
"""
from __future__ import annotations
import json
import re
from typing import TYPE_CHECKING
from crucible.agents.base import ModelClient
from crucible.schemas import Debrief, MoveEvent, OpponentPlaybook, Playbook, UserProfile

if TYPE_CHECKING:
    from crucible.grounding.cellar.graph_store import GraphStore


def _build_system_prompt(
    playbook: Playbook,
    opp_playbook: OpponentPlaybook,
    move_events: list[MoveEvent],
    turning_point_turn: int,
    persona_name: str,
    score: int,
    score_to_beat: int | None,
    user_profile: UserProfile | None = None,
) -> str:
    events_text = "\n".join(
        f"  Turn {e.turn}: [{e.classification}] refs={e.refs} delta={e.position_delta:+.2f} — {e.note}"
        for e in move_events
    )
    opp_ladder_text = "\n".join(
        f"  Rung {i}: {r.position}\n    Would have unlocked if: {r.unlock_condition}"
        for i, r in enumerate(opp_playbook.concession_ladder)
    )
    beat_str = f"Previous best: {score_to_beat}" if score_to_beat is not None else "First round"

    memory_section = ""
    if user_profile and user_profile.recurring_weaknesses:
        weaknesses_text = "\n".join(
            f"  - {w}" for w in user_profile.recurring_weaknesses
        )
        memory_section = f"""
PRIOR COACHING MEMORY (known recurring weaknesses from previous rounds):
{weaknesses_text}

IMPORTANT: explicitly note in persona_note whether a known weakness RECURRED or IMPROVED this round.
Example: "You fixed last round's early-concession problem — new gap is X" or
         "The {persona_name} persona again triggered the recurring pattern of Y."
"""

    return f"""You are a senior legal training coach reviewing a completed {playbook.scenario} round.
This round's score: {score}/100. {beat_str}.

The trainee played against persona: {persona_name}.

TURN-BY-TURN ADJUDICATOR LOG:
{events_text}

TURNING POINT: Turn {turning_point_turn} was identified as the critical moment.

USER-SIDE PLAYBOOK (what they were trying to achieve):
Matter: {playbook.matter_summary}
Objectives: {playbook.objectives}

OPPONENT'S HIDDEN CONCESSION LADDER (revealed now for coaching):
{opp_ladder_text}
{memory_section}
Your task: produce three specific, grounded coaching outputs in JSON:
{{
  "turning_point_explainer": "<2-3 sentences: what went wrong or right at turn {turning_point_turn} AND what the great-lawyer alternative was>",
  "stronger_move": "<the single best alternative move for the worst moment — cite the specific legal hook that would have worked>",
  "persona_note": "<one sentence on how the {persona_name} persona was exploiting this trainee's pattern and how to counter it next round; note if a prior weakness recurred or improved>"
}}

Rules:
- Be specific — reference actual turn numbers, specific legal articles, specific words said
- Never say "you should have been more confident" — that is not coaching, that is vague
- The stronger_move must be actionable: a specific argument with a specific legal ground
- Return ONLY the JSON object above
"""


def _extract_json(raw: str) -> dict:
    raw = raw.strip()
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw, re.DOTALL)
    if m:
        return json.loads(m.group(1), strict=False)
    try:
        return json.loads(raw, strict=False)
    except json.JSONDecodeError:
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start != -1 and end > start:
            return json.loads(raw[start:end], strict=False)
        raise ValueError(f"Could not extract JSON from coach response: {raw[:200]!r}")


class CoachAgent:
    def __init__(
        self,
        client: ModelClient,
        model: str,
        graph_store: "GraphStore | None" = None,
    ) -> None:
        self._client = client
        self._model = model
        self._graph_store = graph_store

    def _enrich_authorities(
        self,
        authorities: list,
        stronger_move_text: str,
    ) -> list:
        """Resolve authorities against the graph and surface any repealed ones.

        If a graph_store is attached:
          1. Resolve each existing authority (set work_uuid + in_force if missing).
          2. If no authorities came from the playbook, search the graph using
             the stronger_move text to find relevant ones.
        """
        if self._graph_store is None:
            return authorities

        from crucible.grounding.cellar.tools import cellar_resolve, cellar_in_force, cellar_search
        from crucible.schemas import Authority

        enriched: list[Authority] = []
        for auth in authorities:
            if isinstance(auth, Authority) and auth.celex and auth.work_uuid is None:
                resolved = cellar_resolve(self._graph_store, auth.celex, auth.pinpoint)
                if resolved:
                    enriched.append(auth.model_copy(update={
                        "work_uuid": resolved.work_uuid,
                        "provision_id": resolved.provision_id,
                        "eli": resolved.eli or auth.eli,
                        "in_force": resolved.in_force,
                    }))
                else:
                    enriched.append(auth)
            else:
                enriched.append(auth)

        # If still empty, search the graph using the stronger_move text
        if not enriched and stronger_move_text:
            hits = cellar_search(self._graph_store, stronger_move_text, top_k=3)
            enriched = [auth for auth, _ in hits]

        return enriched

    def produce_debrief(
        self,
        transcript: list[dict],
        move_events: list[MoveEvent],
        playbook: Playbook,
        opp_playbook: OpponentPlaybook,
        persona_name: str,
        score: int,
        subscores: dict[str, int],
        turning_point_turn: int,
        score_to_beat: int | None,
        biggest_concession: MoveEvent | None,
        biggest_miss: MoveEvent | None,
        biggest_overplay: MoveEvent | None,
        stronger_move_authorities: list,
        user_profile: UserProfile | None = None,
    ) -> Debrief:
        system = _build_system_prompt(
            playbook,
            opp_playbook,
            move_events,
            turning_point_turn,
            persona_name,
            score,
            score_to_beat,
            user_profile,
        )
        raw = self._client.generate(
            model=self._model,
            system=system,
            messages=transcript,
        )
        parsed = _extract_json(raw)

        # Enrich stronger_move_authorities with graph resolution + in-force check
        stronger_move_authorities = self._enrich_authorities(
            stronger_move_authorities,
            parsed.get("stronger_move", ""),
        )

        return Debrief(
            score=score,
            subscores=subscores,
            score_to_beat=score_to_beat,
            turning_point_turn=turning_point_turn,
            turning_point_explainer=str(parsed.get("turning_point_explainer", "")),
            stronger_move=str(parsed.get("stronger_move", "")),
            stronger_move_authorities=stronger_move_authorities,
            biggest_concession=biggest_concession,
            biggest_miss=biggest_miss,
            biggest_overplay=biggest_overplay,
            persona_note=str(parsed.get("persona_note", "")),
        )
